local colors = {
  -- PATCH_OPEN
Normal = {fg = "#D0C7F5", bg = "#342E4D"},
NormalFloat = {link = "Normal"},
Pmenu = {link = "Normal"},
Added = {fg = "#75D1BA"},
BlinkCmpDocBorder = {fg = "#534B71"},
BlinkCmpMenuBorder = {fg = "#534B71"},
Boolean = {fg = "#E779DE"},
Changed = {fg = "#E79B88"},
Character = {fg = "#69CAF7"},
ColorColumn = {bg = "#4E3B68"},
Comment = {fg = "#635A87"},
CompletionBorder = {fg = "#534B71"},
Conditional = {fg = "#E779DE"},
Constant = {fg = "#B09EFA"},
CurSearch = {fg = "#75D1BA", bg = "#43516B"},
Cursor = {bg = "#E779DE"},
CursorLine = {bg = "#403668"},
BlinkCmpMenuSelection = {link = "CursorLine"},
PmenuSel = {link = "CursorLine"},
SnacksPickerCursorLine = {link = "CursorLine"},
CursorLineNr = {fg = "#9377F8", bg = "#403668"},
Debug = {fg = "#E095EF"},
Define = {fg = "#E095EF"},
Delimiter = {fg = "#B09EFA"},
DiagnosticError = {fg = "#E779DE"},
DiagnosticHint = {fg = "#69CAF7"},
DiagnosticInfo = {fg = "#9377F8"},
DiagnosticOk = {fg = "#75D1BA"},
DiagnosticUnderlineError = {sp = "#E779DE", undercurl = true},
DiagnosticUnderlineHint = {sp = "#69CAF7", undercurl = true},
DiagnosticUnderlineInfo = {sp = "#9377F8", undercurl = true},
DiagnosticUnderlineOk = {sp = "#75D1BA", undercurl = true},
DiagnosticUnderlineWarn = {sp = "#E79B88", undercurl = true},
DiagnosticVirtualTextError = {fg = "#E779DE", bg = "#573D6C"},
DiagnosticVirtualTextHint = {fg = "#69CAF7", bg = "#3A456E"},
DiagnosticVirtualTextInfo = {fg = "#9377F8", bg = "#453974"},
DiagnosticVirtualTextOk = {fg = "#75D1BA", bg = "#404863"},
DiagnosticVirtualTextWarn = {fg = "#E79B88", bg = "#614965"},
DiagnosticWarn = {fg = "#E79B88"},
DiffAdd = {fg = "#75D1BA"},
DiffChange = {fg = "#E79B88"},
DiffDelete = {fg = "#E779DE"},
DiffText = {bg = "#815A68"},
Directory = {fg = "#B09EFA", bold = true},
DocumentationBorder = {fg = "#534B71"},
DropBarIconKindFolder = {fg = "#9377F8"},
DropBarIconUIPickPivot = {fg = "#9377F8", bold = true},
Error = {bg = "#7E4A8C"},
ErrorMsg = {fg = "#B09EFA"},
Exception = {fg = "#E779DE"},
FloatBorder = {fg = "#534B71"},
FloatTitle = {fg = "#B09EFA"},
Folded = {bg = "#563F69"},
Function = {fg = "#9377F8"},
GitConflictAncestor = {bg = "#3A5D92"},
GitConflictAncestorLabel = {link = "GitConflictAncestor"},
GitConflictCurrent = {bg = "#744096"},
GitConflictCurrentLabel = {link = "GitConflictCurrent"},
GitConflictIncoming = {bg = "#4C369B"},
GitConflictIncomingLabel = {link = "GitConflictIncoming"},
GitGraphAuthor = {fg = "#69CAF7"},
GitGraphBranch1 = {fg = "#75D1BA"},
GitGraphBranch2 = {fg = "#798FFB"},
GitGraphBranch3 = {fg = "#E79B88"},
GitGraphBranch4 = {fg = "#E095EF"},
GitGraphBranch5 = {fg = "#E779DE"},
GitGraphBranchMsg = {fg = "#B09EFA"},
GitGraphBranchName = {fg = "#9377F8"},
GitGraphBranchTag = {fg = "#E779DE"},
GitGraphHash = {fg = "#E095EF"},
GitGraphTimestamp = {fg = "#B09EFA"},
GrugFarHelpHeaderKey = {fg = "#E779DE"},
GrugFarInputLabel = {fg = "#9377F8"},
Identifier = {fg = "#B09EFA"},
Include = {fg = "#E779DE"},
Keyword = {fg = "#E779DE"},
Label = {fg = "#E779DE"},
LineNr = {fg = "#534B71"},
LineNrAbove = {fg = "#534B71"},
LineNrBelow = {fg = "#534B71"},
Macro = {fg = "#E779DE"},
MatchParen = {fg = "#E095EF", bg = "#5F3D7F"},
MiniFilesDirectory = {fg = "#B09EFA"},
ModeMsg = {fg = "#B09EFA"},
MoreMsg = {fg = "#B09EFA"},
NonText = {fg = "#534B71"},
Number = {fg = "#E095EF"},
Float = {link = "Number"},
Operator = {fg = "#B09EFA"},
PmenuSbar = {bg = "#2D283E"},
PmenuThumb = {bg = "#E779DE"},
PreCondit = {fg = "#E095EF"},
PreProc = {fg = "#E095EF"},
Removed = {fg = "#E779DE"},
RenderMarkdownCode = {bg = "#2D283E"},
RenderMarkdownH1 = {fg = "#E779DE"},
RenderMarkdownH1Bg = {fg = "#E779DE", bg = "#78408C"},
RenderMarkdownH2 = {fg = "#75D1BA"},
RenderMarkdownH2Bg = {fg = "#75D1BA", bg = "#4A6478"},
RenderMarkdownH3 = {fg = "#798FFB"},
RenderMarkdownH3Bg = {fg = "#798FFB", bg = "#363B9B"},
RenderMarkdownH4 = {fg = "#E79B88"},
RenderMarkdownH4Bg = {fg = "#E79B88", bg = "#7F5369"},
RenderMarkdownH5 = {fg = "#9377F8"},
RenderMarkdownH5Bg = {fg = "#9377F8", bg = "#4C369B"},
RenderMarkdownH6 = {fg = "#E095EF"},
RenderMarkdownH6Bg = {fg = "#E095EF", bg = "#744096"},
Repeat = {fg = "#E779DE"},
Search = {fg = "#9377F8", bg = "#433678"},
NoiceVirtualText = {link = "Search"},
SnacksDashboardDesc = {fg = "#B09EFA"},
SnacksDashboardFooter = {fg = "#B09EFA"},
SnacksDashboardHeader = {fg = "#E095EF"},
SnacksDashboardIcon = {fg = "#9377F8"},
SnacksDashboardKey = {fg = "#9377F8"},
SnacksDashboardSpecial = {fg = "#E779DE"},
SnacksIndent = {fg = "#433D5C"},
SnacksIndentScope = {fg = "#B09EFA"},
Special = {fg = "#E779DE"},
SpecialChar = {fg = "#E779DE"},
SpecialComment = {fg = "#9377F8"},
Statement = {fg = "#798FFB"},
StatusLine = {bg = "#342E4D"},
StorageClass = {fg = "#E095EF"},
String = {fg = "#E095EF"},
Structure = {fg = "#E095EF"},
TabLine = {bg = "#342E4D"},
TabLineFill = {bg = "#342E4D"},
TabLineSel = {bg = "#342E4D"},
Tag = {fg = "#B09EFA"},
Title = {fg = "#E779DE", bold = true},
Todo = {fg = "#69CAF7", bold = true},
Type = {fg = "#75D1BA"},
Typedef = {fg = "#75D1BA"},
Underlined = {bold = true},
VertSplit = {fg = "#534B71"},
Winseparator = {link = "VertSplit"},
Visual = {bg = "#53438E"},
WarningMsg = {fg = "#B09EFA"},
Whitespace = {fg = "#534B71"},
WinBar = {fg = "#D0C7F5"},
WinBarNC = {link = "WinBar"},
illuminatedWord = {bg = "#463681"},
IlluminatedWordRead = {link = "illuminatedWord"},
IlluminatedWordText = {link = "illuminatedWord"},
IlluminatedWordWrite = {link = "illuminatedWord"},
LspReferenceRead = {link = "illuminatedWord"},
LspReferenceText = {link = "illuminatedWord"},
LspReferenceWrite = {link = "illuminatedWord"},
QuickFixLine = {link = "illuminatedWord"},
illuminatedCurWord = {link = "illuminatedWord"},
["@attribute"] = {fg = "#9377F8"},
["@constant.builtin"] = {fg = "#69CAF7"},
["@constructor"] = {fg = "#75D1BA"},
["@constructor.lua"] = {fg = "#9377F8"},
["@function.builtin"] = {fg = "#9377F8"},
["@keyword.function"] = {fg = "#E779DE"},
["@keyword.modifier"] = {fg = "#E779DE"},
["@keyword.operator"] = {fg = "#E779DE"},
["@keyword.return"] = {fg = "#E779DE"},
["@module"] = {fg = "#E79B88"},
["@namespace"] = {fg = "#E79B88"},
["@parameter"] = {fg = "#B09EFA"},
["@type.builtin"] = {fg = "#69CAF7"},
["@variable"] = {fg = "#D0C7F5"},
["@variable.builtin"] = {fg = "#69CAF7"},
["@variable.parameter"] = {fg = "#D0C7F5"},
  -- PATCH_CLOSE
}

-- colorschemes generally want to do this
vim.cmd("highlight clear")
vim.cmd("set t_Co=256")
vim.cmd("let g:colors_name='nyappuccin'")

-- apply highlight groups
for group, attrs in pairs(colors) do
  vim.api.nvim_set_hl(0, group, attrs)
end
